#pragma once

#ifndef PSX_MINECRAFT_ASSET_INDICES_H
#define PSX_MINECRAFT_ASSET_INDICES_H

#define ASSET_TEXTURES_INDEX 0
#define ASSET_TEXTURES_TERRAIN_INDEX 0
#define ASSET_GUI_INDEX 1
#define ASSET_GUI_GUI_INDEX 0

#endif // PSX_MINECRAFT_ASSET_INDICES_H    
