#pragma once

#ifndef PSXMC__RESOURCES__ASSET_INDICES_H
#define PSXMC__RESOURCES__ASSET_INDICES_H

#define ASSET_BUNDLE__STATIC 0
#define ASSET_TEXTURE__STATIC__FONT 0
#define ASSET_TEXTURE__STATIC__GUI 1
#define ASSET_TEXTURE__STATIC__ITEMS 2
#define ASSET_TEXTURE__STATIC__TERRAIN 3
#define ASSET_TEXTURE__STATIC__WEATHER 4

#define ASSET_BUNDLE__GUI 1
#define ASSET_TEXTURE__GUI__CRAFTING 0
#define ASSET_TEXTURE__GUI__INVENTORY 1

#define ASSET_BUNDLES_COUNT 3

#endif // PSXMC__RESOURCES__ASSET_INDICES_H
