#pragma once

#ifndef PSXMC__RESOURCES__ASSET_INDICES_H
#define PSXMC__RESOURCES__ASSET_INDICES_H

#define ASSET_BUNDLE__START 0
#define ASSET_TEXTURE__START__MOJANG 0

#define ASSET_BUNDLE__STATIC 1
#define ASSET_TEXTURE__STATIC__FONT 0
#define ASSET_TEXTURE__STATIC__GUI_PART 1
#define ASSET_TEXTURE__STATIC__ITEMS 2
#define ASSET_TEXTURE__STATIC__TERRAIN 3
#define ASSET_TEXTURE__STATIC__WEATHER 4

#define ASSET_BUNDLE__MENU 2
#define ASSET_TEXTURE__MENU__LOGO 0

#define ASSET_BUNDLE__GUI 3
#define ASSET_TEXTURE__GUI__CRAFTING 0
#define ASSET_TEXTURE__GUI__INVENTORY 1

#define ASSET_BUNDLES_COUNT 5

#endif // PSXMC__RESOURCES__ASSET_INDICES_H
