#pragma once

#ifndef PSX_MINECRAFT_SLOT_H
#define PSX_MINECRAFT_SLOT_H

#include <stdbool.h>
#include <psxgte.h>

#include "../items/item.h"

typedef struct {
    IItem* item;
    DVECTOR position;
    DVECTOR dimensions;
    bool blocked;
} Slot;

#ifndef INV_SLOT_WIDTH
#define INV_SLOT_WIDTH 16
#endif
#ifndef INV_SLOT_HEIGHT
#define INV_SLOT_HEIGHT 16
#endif
#ifndef INV_SLOT_DIMS
#define INV_SLOT_DIMS (DVECTOR) { \
    .vx = INV_SLOT_WIDTH, \
    .vy = INV_SLOT_HEIGHT \
}
#endif

#ifndef INV_SLOT_POS_DIFF
#define INV_SLOT_POS_DIFF 18
#endif

// Player Inventory [START]
// TODO: Figure out these values

// = Player Inventory - Armor [START]
// +-+
// | |
// +-+
// | |
// +-+
// | |
// +-+
// | |
// +-+

#ifndef PLAYER_INV_ARMOR_HELMET_POS_X
#define PLAYER_INV_ARMOR_HELMET_POS_X 0
#endif
#ifndef PLAYER_INV_ARMOR_HELMET_POS_Y
#define PLAYER_INV_ARMOR_HELMET_POS_Y 0
#endif
#define PLAYER_INV_ARMOR_HELMET_POS (DEVECTOR) { \
    .vx = PLAYER_INV_ARMOR_HELMET_POS_X, \
    .vy = PLAYER_INV_ARMOR_HELMET_POS_Y \
}

#ifndef PLAYER_INV_ARMOR_CHESTPLATE_POS_X
#define PLAYER_INV_ARMOR_CHESTPLATE_POS_X PLAYER_INV_ARMOR_HELMET_POS_X
#endif
#ifndef PLAYER_INV_ARMOR_CHESTPLATE_POS_Y
#define PLAYER_INV_ARMOR_CHESTPLATE_POS_Y (PLAYER_INV_ARMOR_HELMET_POS_Y + INV_SLOT_POS_DIFF)
#endif
#define PLAYER_INV_ARMOR_CHESTPLATE_POS (DEVECTOR) { \
    .vx = PLAYER_INV_ARMOR_CHESTPLATE_POS_X, \
    .vy = PLAYER_INV_ARMOR_CHESTPLATE_POS_Y \
}

#ifndef PLAYER_INV_ARMOR_LEGGINGS_POS_X
#define PLAYER_INV_ARMOR_LEGGINGS_POS_X PLAYER_INV_ARMOR_CHESTPLATE_POS_X
#endif
#ifndef PLAYER_INV_ARMOR_LEGGINGS_POS_Y
#define PLAYER_INV_ARMOR_LEGGINGS_POS_Y (PLAYER_INV_ARMOR_CHESTPLATE_POS_Y + INV_SLOT_POS_DIFF)
#endif
#define PLAYER_INV_ARMOR_LEGGINGS_POS (DEVECTOR) { \
    .vx = PLAYER_INV_ARMOR_LEGGINGS_POS_X, \
    .vy = PLAYER_INV_ARMOR_LEGGINGS_POS_Y \
}

#ifndef PLAYER_INV_ARMOR_BOOTS_POS_X
#define PLAYER_INV_ARMOR_BOOTS_POS_X PLAYER_INV_ARMOR_LEGGINGS_POS_X
#endif
#ifndef PLAYER_INV_ARMOR_BOOTS_POS_Y
#define PLAYER_INV_ARMOR_BOOTS_POS_Y (PLAYER_INV_ARMOR_LEGGINGS_POS_Y + INV_SLOT_POS_DIFF)
#endif
#define PLAYER_INV_ARMOR_BOOTS_POS (DEVECTOR) { \
    .vx = PLAYER_INV_ARMOR_BOOTS_POS_X, \
    .vy = PLAYER_INV_ARMOR_BOOTS_POS_Y \
}

// = Player Inventory - Armor [END]

// = Player Inventory - Crafting [START]
// +-+-+
// | | |
// +-+-+
// | | |
// +-+-+

#ifndef PLAYER_INV_CRAFTING_TOP_LEFT_POS_X
#define PLAYER_INV_CRAFTING_TOP_LEFT_POS_X 0
#endif
#ifndef PLAYER_INV_CRAFTING_TOP_LEFT_POS_Y
#define PLAYER_INV_CRAFTING_TOP_LEFT_POS_Y 0
#endif
#define PLAYER_INV_CRAFTING_TOP_LEFT_POS (DEVECTOR) { \
    .vx = PLAYER_INV_CRAFTING_TOP_LEFT_POS_X, \
    .vy = PLAYER_INV_CRAFTING_TOP_LEFT_POS_Y \
}

#ifndef PLAYER_INV_CRAFTING_TOP_RIGHT_POS_X
#define PLAYER_INV_CRAFTING_TOP_RIGHT_POS_X (PLAYER_INV_CRAFTING_TOP_LEFT_POS_X + INV_SLOT_POS_DIFF)
#endif
#ifndef PLAYER_INV_CRAFTING_TOP_RIGHT_POS_Y
#define PLAYER_INV_CRAFTING_TOP_RIGHT_POS_Y 0
#endif
#define PLAYER_INV_CRAFTING_TOP_RIGHT_POS (DEVECTOR) { \
    .vx = PLAYER_INV_CRAFTING_TOP_RIGHT_POS_X, \
    .vy = PLAYER_INV_CRAFTING_TOP_RIGHT_POS_Y \
}

#ifndef PLAYER_INV_CRAFTING_BOTOM_LEFT_POS_X
#define PLAYER_INV_CRAFTING_BOTOM_LEFT_POS_X 0
#endif
#ifndef PLAYER_INV_CRAFTING_BOTOM_LEFT_POS_Y
#define PLAYER_INV_CRAFTING_BOTOM_LEFT_POS_Y (PLAYER_INV_CRAFTING_TOP_LEFT_POS_Y + INV_SLOT_POS_DIFF)
#endif
#define PLAYER_INV_CRAFTING_BOTOM_LEFT_POS (DEVECTOR) { \
    .vx = PLAYER_INV_CRAFTING_BOTOM_LEFT_POS_X, \
    .vy = PLAYER_INV_CRAFTING_BOTOM_LEFT_POS_Y \
}

#ifndef PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS_X
#define PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS_X (PLAYER_INV_CRAFTING_TOP_LEFT_POS_X + INV_SLOT_POS_DIFF)
#endif
#ifndef PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS_Y
#define PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS_Y (PLAYER_INV_CRAFTING_TOP_LEFT_POS_Y + INV_SLOT_POS_DIFF)
#endif
#define PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS (DEVECTOR) { \
    .vx = PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS_X, \
    .vy = PLAYER_INV_CRAFTING_BOTTOM_RIGHT_POS_Y \
}

// = Player Inventory - Crafing [END]

// Player Inventory [END]

#endif // PSX_MINECRAFT_SLOT_H
