#include "item_tool.h"

const fixedi32 TOOL_MATERIAL_SPEED_MULTIPLIER[TOOL_MATERIAL_COUNT] = {
    [TOOLMATERIAL_NONE] = 1 << FIXED_POINT_SHIFT,
    [TOOLMATERIAL_WOOD] = 2 << FIXED_POINT_SHIFT,
    [TOOLMATERIAL_STONE] = 4 << FIXED_POINT_SHIFT,
    [TOOLMATERIAL_IRON] = 6 << FIXED_POINT_SHIFT,
    [TOOLMATERIAL_GOLD] = 12 << FIXED_POINT_SHIFT,
    [TOOLMATERIAL_DIAMOND] = 8 << FIXED_POINT_SHIFT
};