#pragma once

#ifndef _PSXMC__GAME_WORLD_CHUNK__CHUNK_DEFINES_H_
#define _PSXMC__GAME_WORLD_CHUNK__CHUNK_DEFINES_H_

#define CHUNK_SIZE 8
#define CHUNK_BLOCK_SIZE (CHUNK_SIZE * BLOCK_SIZE)
#define CHUNK_DATA_SIZE (CHUNK_SIZE * CHUNK_SIZE * CHUNK_SIZE)
#define CHUNK_DIRECTIONS 3
#define CHUNK_AXIS_NEIGHBOURS (CHUNK_DIRECTIONS * 2)
// -1 = unlimited
#define CHUNK_LIGHT_ADD_BLOCK_UPDATES_PER_TICK -1
#define CHUNK_LIGHT_ADD_SKY_UPDATES_PER_TICK -1
#define CHUNK_LIGHT_REMOVE_BLOCK_UPDATES_PER_TICK -1
#define CHUNK_LIGHT_REMOVE_SKY_UPDATES_PER_TICK -1

#endif // _PSXMC__GAME_WORLD_CHUNK__CHUNK_DEFINES_H_
