#pragma once

#ifndef PSXMC_BLOCK_ID_H
#define PSXMC_BLOCK_ID_H

#include "../../util/preprocessor.h"

#define BLOCK_LIST(f) \
    f(ENUM_ENTRY_ORD(BLOCKID_AIR,0)), \
    f(ENUM_ENTRY_ORD(BLOCKID_STONE,1)), \
    f(ENUM_ENTRY_ORD(BLOCKID_GRASS,2)), \
    f(ENUM_ENTRY_ORD(BLOCKID_DIRT,3)), \
    f(ENUM_ENTRY_ORD(BLOCKID_COBBLESTONE,4)), \
    f(ENUM_ENTRY_ORD(BLOCKID_PLANK,5)), \
    f(ENUM_ENTRY_ORD(BLOCKID_SAPLING,6)), \
    f(ENUM_ENTRY_ORD(BLOCKID_BEDROCK,7)), \
    f(ENUM_ENTRY_ORD(BLOCKID_WATER_FLOWING,8)), \
    f(ENUM_ENTRY_ORD(BLOCKID_WATER_STILL,9)), \
    f(ENUM_ENTRY_ORD(BLOCKID_LAVA_FLOWING,10)), \
    f(ENUM_ENTRY_ORD(BLOCKID_LAVA_STILL, 11)), \
    f(ENUM_ENTRY_ORD(BLOCKID_SAND, 12)), \
    f(ENUM_ENTRY_ORD(BLOCKID_GRAVEL, 13)), \
    f(ENUM_ENTRY_ORD(BLOCKID_GOLD_ORE, 14)), \
    f(ENUM_ENTRY_ORD(BLOCKID_IRON_ORE, 15)), \
    f(ENUM_ENTRY_ORD(BLOCKID_COAL_ORE, 16)), \
    f(ENUM_ENTRY_ORD(BLOCKID_LOG, 17)), \
    f(ENUM_ENTRY_ORD(BLOCKID_LEAVES, 18)), \
    f(ENUM_ENTRY_ORD(BLOCKID_SPONGE, 19)), \
    f(ENUM_ENTRY_ORD(BLOCKID_GLASS, 20))

typedef enum {
    BLOCK_LIST(enumConstruct)
} EBlockID;

extern const char* EBLOCKID_NAMES[];

#define blockIdStringify(id) EBLOCKID_NAMES[(id)]

#endif // PSXMC_BLOCK_ID_H
