#pragma once

#ifndef PSXMC_BLOCK_ID_H
#define PSXMC_BLOCK_ID_H

#include "../../util/preprocessor.h"

#define BLOCK_LIST(f) \
    f(ENUM_ENTRY_ORD(BLOCKID_AIR,0)) \
    f(ENUM_ENTRY_ORD(BLOCKID_STONE,1)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GRASS,2)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DIRT,3)) \
    f(ENUM_ENTRY_ORD(BLOCKID_COBBLESTONE,4)) \
    f(ENUM_ENTRY_ORD(BLOCKID_PLANK,5)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SAPLING,6)) \
    f(ENUM_ENTRY_ORD(BLOCKID_BEDROCK,7)) \
    f(ENUM_ENTRY_ORD(BLOCKID_WATER_FLOWING,8)) \
    f(ENUM_ENTRY_ORD(BLOCKID_WATER_STILL,9)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LAVA_FLOWING,10)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LAVA_STILL, 11)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SAND, 12)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GRAVEL, 13)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GOLD_ORE, 14)) \
    f(ENUM_ENTRY_ORD(BLOCKID_IRON_ORE, 15)) \
    f(ENUM_ENTRY_ORD(BLOCKID_COAL_ORE, 16)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LOG, 17)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LEAVES, 18)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SPONGE, 19)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GLASS, 20)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LAPIS_ORE, 21)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LAPIS_BLOCK, 22)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DISPENSER, 23)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SANDSTONE, 24)) \
    f(ENUM_ENTRY_ORD(BLOCKID_NOTEBLOCK, 25)) \
    f(ENUM_ENTRY_ORD(BLOCKID_BED_BLOCK, 26)) \
    f(ENUM_ENTRY_ORD(BLOCKID_POWERED_RAIL, 27)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DETECTOR_RAIL, 28)) \
    f(ENUM_ENTRY_ORD(BLOCKID_STICKY_PISTON, 29)) \
    f(ENUM_ENTRY_ORD(BLOCKID_COBWEB, 30)) \
    f(ENUM_ENTRY_ORD(BLOCKID_TALL_GRASS, 31)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DEAD_BUSH, 32)) \
    f(ENUM_ENTRY_ORD(BLOCKID_PISTON, 33)) \
    f(ENUM_ENTRY_ORD(BLOCKID_PISTON_HEAD, 34)) \
    f(ENUM_ENTRY_ORD(BLOCKID_WOOL, 35)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GRASS_TOP, 36)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DANDELION, 37)) \
    f(ENUM_ENTRY_ORD(BLOCKID_ROSE, 38)) \
    f(ENUM_ENTRY_ORD(BLOCKID_BROWN_MUSHROOM, 39)) \
    f(ENUM_ENTRY_ORD(BLOCKID_RED_MUSHROOM, 40)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GOLD_BLOCK, 41)) \
    f(ENUM_ENTRY_ORD(BLOCKID_IRON_BLOCK, 42)) \
    f(ENUM_ENTRY_ORD(BLOCKID_FULL_SLAB, 43)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SLAB, 44)) \
    f(ENUM_ENTRY_ORD(BLOCKID_BRICK_BLOCK, 45)) \
    f(ENUM_ENTRY_ORD(BLOCKID_TNT, 46)) \
    f(ENUM_ENTRY_ORD(BLOCKID_BOOKSHELF, 47)) \
    f(ENUM_ENTRY_ORD(BLOCKID_MOSSY_COBBLESTONE, 48)) \
    f(ENUM_ENTRY_ORD(BLOCKID_OBSIDIAN, 49)) \
    f(ENUM_ENTRY_ORD(BLOCKID_TORCH, 50)) \
    f(ENUM_ENTRY_ORD(BLOCKID_FIRE, 51)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SPAWNER, 52)) \
    f(ENUM_ENTRY_ORD(BLOCKID_WOODEN_STAIRS, 53)) \
    f(ENUM_ENTRY_ORD(BLOCKID_CHEST, 54)) \
    f(ENUM_ENTRY_ORD(BLOCKID_REDSTONE, 55)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DIAMOND_ORE, 56)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DIAMOND_BLOCK, 57)) \
    f(ENUM_ENTRY_ORD(BLOCKID_CRAFTING_TABLE, 58)) \
    f(ENUM_ENTRY_ORD(BLOCKID_CROPS, 59)) \
    f(ENUM_ENTRY_ORD(BLOCKID_FARMLAND, 60)) \
    f(ENUM_ENTRY_ORD(BLOCKID_FURNACE, 61)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_0, 62)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_1, 63)) \
    f(ENUM_ENTRY_ORD(BLOCKID_DOOR_BLOCK, 64)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LADDER, 65)) \
    f(ENUM_ENTRY_ORD(BLOCKID_RAIL, 66)) \
    f(ENUM_ENTRY_ORD(BLOCKID_COBBLESTON_STAIRS, 67)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_2, 68)) \
    f(ENUM_ENTRY_ORD(BLOCKID_LEVER, 69)) \
    f(ENUM_ENTRY_ORD(BLOCKID_STONE_PRESSURE_PLATE, 70)) \
    f(ENUM_ENTRY_ORD(BLOCKID_IRON_DOOR_BLOCK, 71)) \
    f(ENUM_ENTRY_ORD(BLOCKID_WOODEN_PRESSURE_PLATE, 72)) \
    f(ENUM_ENTRY_ORD(BLOCKID_REDSTONE_ORE, 73)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_3, 74)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_4, 75)) \
    f(ENUM_ENTRY_ORD(BLOCKID_REDSTONE_TORCH, 76)) \
    f(ENUM_ENTRY_ORD(BLOCKID_STONE_BUTTON, 77)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SNOW_LAYER, 78)) \
    f(ENUM_ENTRY_ORD(BLOCKID_ICE, 79)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SNOW, 80)) \
    f(ENUM_ENTRY_ORD(BLOCKID_CACTUS, 81)) \
    f(ENUM_ENTRY_ORD(BLOCKID_CLAY_BLOCK, 82)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SUGAR_CANE_BLOCK, 83)) \
    f(ENUM_ENTRY_ORD(BLOCKID_JUKEBOX, 84)) \
    f(ENUM_ENTRY_ORD(BLOCKID_FENCE, 85)) \
    f(ENUM_ENTRY_ORD(BLOCKID_PUMPKIN, 86)) \
    f(ENUM_ENTRY_ORD(BLOCKID_NETHERRACK, 87)) \
    f(ENUM_ENTRY_ORD(BLOCKID_SOUL_SAND, 88)) \
    f(ENUM_ENTRY_ORD(BLOCKID_GLOWSTONE, 89)) \
    f(ENUM_ENTRY_ORD(BLOCKID_PORTAL, 90)) \
    f(ENUM_ENTRY_ORD(BLOCKID_JACK_O_LANTERN, 91)) \
    f(ENUM_ENTRY_ORD(BLOCKID_CAKE, 92)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_5, 93)) \
    f(ENUM_ENTRY_ORD(BLOCKID_UNUSED_6, 94)) \
    f(ENUM_ENTRY_ORD(BLOCKID_TRAPPED_CHEST, 95)) \
    f(ENUM_ENTRY_ORD(BLOCKID_TRAPDOOR, 96))

#define BLOCK_COUNT (BLOCK_LIST(enumCount) 0)

typedef enum EBlockID {
    BLOCK_LIST(enumConstruct)
} EBlockID;

extern const char* EBLOCKID_NAMES[];

#define blockIdStringify(id) EBLOCKID_NAMES[(id)]

#endif // PSXMC_BLOCK_ID_H
