#pragma once

#ifndef PSXMC_ITEM_ID_H
#define PSXMC_ITEM_ID_H

#include "../../util/preprocessor.h"

#define ITEM_LIST(f) \
    f(ENUM_ENTRY_ORD(ITEMID_AIR,0)), \
    f(ENUM_ENTRY_ORD(ITEMID_STONE,1)), \
    f(ENUM_ENTRY_ORD(ITEMID_GRASS,2)), \
    f(ENUM_ENTRY_ORD(ITEMID_DIRT,3)), \
    f(ENUM_ENTRY_ORD(ITEMID_COBBLESTONE,4)), \
    f(ENUM_ENTRY_ORD(ITEMID_PLANK,5)), \
    f(ENUM_ENTRY_ORD(ITEMID_SAPLING,6)), \
    f(ENUM_ENTRY_ORD(ITEMID_BEDROCK,7)), \
    f(ENUM_ENTRY_ORD(ITEMID_WATER_FLOWING,8)), \
    f(ENUM_ENTRY_ORD(ITEMID_WATER_STILL,9)), \
    f(ENUM_ENTRY_ORD(ITEMID_LAVA_FLOWING,10)), \
    f(ENUM_ENTRY_ORD(ITEMID_LAVA_STILL, 11)), \
    f(ENUM_ENTRY_ORD(ITEMID_SAND, 12)), \
    f(ENUM_ENTRY_ORD(ITEMID_GRAVEL, 13)), \
    f(ENUM_ENTRY_ORD(ITEMID_GOLD_ORE, 14)), \
    f(ENUM_ENTRY_ORD(ITEMID_IRON_ORE, 15)), \
    f(ENUM_ENTRY_ORD(ITEMID_COAL_ORE, 16)), \
    f(ENUM_ENTRY_ORD(ITEMID_LOG, 17)), \
    f(ENUM_ENTRY_ORD(ITEMID_LEAVES, 18)), \
    f(ENUM_ENTRY_ORD(ITEMID_SPONGE, 19)), \
    f(ENUM_ENTRY_ORD(ITEMID_GLASS, 20)), \
    f(ENUM_ENTRY_ORD(ITEMID_LAPIS_ORE, 21)), \
    f(ENUM_ENTRY_ORD(ITEMID_LAPIS_BLOCK, 22)), \
    f(ENUM_ENTRY_ORD(ITEMID_DISPENSER, 23)), \
    f(ENUM_ENTRY_ORD(ITEMID_SANDSTONE, 24)), \
    f(ENUM_ENTRY_ORD(ITEMID_NOTEBLOCK, 25)), \
    f(ENUM_ENTRY_ORD(ITEMID_BED_BLOCK, 26)), \
    f(ENUM_ENTRY_ORD(ITEMID_POWERED_RAIL, 27)), \
    f(ENUM_ENTRY_ORD(ITEMID_DETECTOR_RAIL, 28)), \
    f(ENUM_ENTRY_ORD(ITEMID_STICKY_PISTON, 29)), \
    f(ENUM_ENTRY_ORD(ITEMID_COBWEB, 30)), \
    f(ENUM_ENTRY_ORD(ITEMID_TALL_GRASS, 31)), \
    f(ENUM_ENTRY_ORD(ITEMID_DEAD_BUSH, 32)), \
    f(ENUM_ENTRY_ORD(ITEMID_PISTON, 33)), \
    f(ENUM_ENTRY_ORD(ITEMID_PISTON_HEAD, 34)), \
    f(ENUM_ENTRY_ORD(ITEMID_WOOL, 35)), \
    f(ENUM_ENTRY_ORD(ITEMID_GRASS_TOP, 36)), \
    f(ENUM_ENTRY_ORD(ITEMID_DANDELION, 37)), \
    f(ENUM_ENTRY_ORD(ITEMID_ROSE, 38)), \
    f(ENUM_ENTRY_ORD(ITEMID_BROWN_MUSHROOM, 39)), \
    f(ENUM_ENTRY_ORD(ITEMID_RED_MUSHROOM, 40)), \
    f(ENUM_ENTRY_ORD(ITEMID_GOLD_BLOCK, 41)), \
    f(ENUM_ENTRY_ORD(ITEMID_IRON_BLOCK, 42)), \
    f(ENUM_ENTRY_ORD(ITEMID_FULL_SLAB, 43)), \
    f(ENUM_ENTRY_ORD(ITEMID_SLAB, 44)), \
    f(ENUM_ENTRY_ORD(ITEMID_BRICK_BLOCK, 45)), \
    f(ENUM_ENTRY_ORD(ITEMID_TNT, 46)), \
    f(ENUM_ENTRY_ORD(ITEMID_BOOKSHELF, 47)), \
    f(ENUM_ENTRY_ORD(ITEMID_MOSSY_COBBLESTONE, 48)), \
    f(ENUM_ENTRY_ORD(ITEMID_OBSIDIAN, 49)), \
    f(ENUM_ENTRY_ORD(ITEMID_TORCH, 50)), \
    f(ENUM_ENTRY_ORD(ITEMID_FIRE, 51)), \
    f(ENUM_ENTRY_ORD(ITEMID_SPAWNER, 52)), \
    f(ENUM_ENTRY_ORD(ITEMID_WOODEN_STAIRS, 53)), \
    f(ENUM_ENTRY_ORD(ITEMID_CHEST, 54)), \
    f(ENUM_ENTRY_ORD(ITEMID_REDSTONE, 55)), \
    f(ENUM_ENTRY_ORD(ITEMID_DIAMOND_ORE, 56)), \
    f(ENUM_ENTRY_ORD(ITEMID_DIAMOND_BLOCK, 57)), \
    f(ENUM_ENTRY_ORD(ITEMID_CRAFTING_TABLE, 58)), \
    f(ENUM_ENTRY_ORD(ITEMID_CROPS, 59)), \
    f(ENUM_ENTRY_ORD(ITEMID_FARMLAND, 60)), \
    f(ENUM_ENTRY_ORD(ITEMID_FURNACE, 61)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_0, 62)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_1, 63)), \
    f(ENUM_ENTRY_ORD(ITEMID_DOOR_BLOCK, 64)), \
    f(ENUM_ENTRY_ORD(ITEMID_LADDER, 65)), \
    f(ENUM_ENTRY_ORD(ITEMID_RAIL, 66)), \
    f(ENUM_ENTRY_ORD(ITEMID_COBBLESTON_STAIRS, 67)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_2, 68)), \
    f(ENUM_ENTRY_ORD(ITEMID_LEVER, 69)), \
    f(ENUM_ENTRY_ORD(ITEMID_STONE_PRESSURE_PLATE, 70)), \
    f(ENUM_ENTRY_ORD(ITEMID_IRON_DOOR_BLOCK, 71)), \
    f(ENUM_ENTRY_ORD(ITEMID_WOODEN_PRESSURE_PLATE, 72)), \
    f(ENUM_ENTRY_ORD(ITEMID_REDSTONE_ORE, 73)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_3, 74)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_4, 75)), \
    f(ENUM_ENTRY_ORD(ITEMID_REDSTONE_TORCH, 76)), \
    f(ENUM_ENTRY_ORD(ITEMID_STONE_BUTTON, 77)), \
    f(ENUM_ENTRY_ORD(ITEMID_SNOW_LAYER, 78)), \
    f(ENUM_ENTRY_ORD(ITEMID_ICE, 79)), \
    f(ENUM_ENTRY_ORD(ITEMID_SNOW, 80)), \
    f(ENUM_ENTRY_ORD(ITEMID_CACTUS, 81)), \
    f(ENUM_ENTRY_ORD(ITEMID_CLAY_BLOCK, 82)), \
    f(ENUM_ENTRY_ORD(ITEMID_SUGAR_CANE_BLOCK, 83)), \
    f(ENUM_ENTRY_ORD(ITEMID_JUKEBOX, 84)), \
    f(ENUM_ENTRY_ORD(ITEMID_FENCE, 85)), \
    f(ENUM_ENTRY_ORD(ITEMID_PUMPKIN, 86)), \
    f(ENUM_ENTRY_ORD(ITEMID_NETHERRACK, 87)), \
    f(ENUM_ENTRY_ORD(ITEMID_SOUL_SAND, 88)), \
    f(ENUM_ENTRY_ORD(ITEMID_GLOWSTONE, 89)), \
    f(ENUM_ENTRY_ORD(ITEMID_PORTAL, 90)), \
    f(ENUM_ENTRY_ORD(ITEMID_JACK_O_LANTERN, 91)), \
    f(ENUM_ENTRY_ORD(ITEMID_CAKE, 92)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_5, 93)), \
    f(ENUM_ENTRY_ORD(ITEMID_UNUSED_6, 94)), \
    f(ENUM_ENTRY_ORD(ITEMID_TRAPPED_CHEST, 95)), \
    f(ENUM_ENTRY_ORD(ITEMID_TRAPDOOR, 96))

typedef enum {
    ITEM_LIST(enumConstruct)
} EItemID;

extern const char* EITEMID_NAMES[];

#define itemIdStringify(id) EITEMID_NAMES[(id)]

#endif // PSXMC_ITEM_ID_H
