#pragma once

#ifndef PSX_MINECRAFT_ITEM_ID_H
#define PSX_MINECRAFT_ITEM_ID_H

#include "../../util/preprocessor.h"

#define ITEM_LIST(f) \
    f(ENUM_ENTRY_ORD(ITEMID_AIR,0)), \
    f(ENUM_ENTRY_ORD(ITEMID_STONE,1)), \
    f(ENUM_ENTRY_ORD(ITEMID_GRASS,2)), \
    f(ENUM_ENTRY_ORD(ITEMID_DIRT,3)), \
    f(ENUM_ENTRY_ORD(ITEMID_COBBLESTONE,4)), \
    f(ENUM_ENTRY_ORD(ITEMID_PLANK,5)), \
    f(ENUM_ENTRY_ORD(ITEMID_SAPLING,6)), \
    f(ENUM_ENTRY_ORD(ITEMID_BEDROCK,7)), \
    f(ENUM_ENTRY_ORD(ITEMID_WATER_FLOWING,8)), \
    f(ENUM_ENTRY_ORD(ITEMID_WATER_STILL,9)), \
    f(ENUM_ENTRY_ORD(ITEMID_LAVA_FLOWING,10)), \
    f(ENUM_ENTRY_ORD(ITEMID_LAVA_STILL, 11)), \
    f(ENUM_ENTRY_ORD(ITEMID_SAND, 12)), \
    f(ENUM_ENTRY_ORD(ITEMID_GRAVEL, 13)), \
    f(ENUM_ENTRY_ORD(ITEMID_GOLD_ORE, 14)), \
    f(ENUM_ENTRY_ORD(ITEMID_IRON_ORE, 15)), \
    f(ENUM_ENTRY_ORD(ITEMID_COAL_ORE, 16)), \
    f(ENUM_ENTRY_ORD(ITEMID_LOG, 17)), \
    f(ENUM_ENTRY_ORD(ITEMID_LEAVES, 18)), \
    f(ENUM_ENTRY_ORD(ITEMID_SPONGE, 19)), \
    f(ENUM_ENTRY_ORD(ITEMID_GLASS, 20))

typedef enum {
    ITEM_LIST(enumConstruct)
} EItemID;

extern const char* EITEMID_NAMES[];

#define itemIdStringify(id) EITEMID_NAMES[(id)]

#endif // PSX_MINECRAFT_ITEM_ID_H
