#include "bindings.h"

#include "../../util/preprocessor.h"

// TODO: Convert to left stick
WEAK PadButton BINDING_MOVE_FORWARD = PAD_UP;
WEAK PadButton BINDING_MOVE_BACKWARD = PAD_DOWN;
WEAK PadButton BINDING_MOVE_LEFT = PAD_LEFT;
WEAK PadButton BINDING_MOVE_RIGHT = PAD_RIGHT;

// TODO: Convert to right stick
WEAK PadButton BINDING_LOOK_UP = PAD_TRIANGLE;
WEAK PadButton BINDING_LOOK_DOWN = PAD_CROSS;
WEAK PadButton BINDING_LOOK_LEFT = PAD_SQUARE;
WEAK PadButton BINDING_LOOK_RIGHT = PAD_CIRCLE;

WEAK PadButton BINDING_JUMP = PAD_R1;
WEAK PadButton BINDING_SNEAK = PAD_L1;

WEAK PadButton BINDING_ATTACK = PAD_R2;
WEAK PadButton BINDING_USE = PAD_L2;

WEAK PadButton BINDING_DROP_ITEM = PAD_CIRCLE;
WEAK PadButton BINDING_OPEN_INVENTORY = PAD_START; // PAD_TRIANGLE
WEAK PadButton BINDING_CURSOR_CLICK = PAD_CROSS;
// Need to adjust these since they don't feel right for these actions
WEAK PadButton BINDING_PREVIOUS = PAD_L3;
WEAK PadButton BINDING_NEXT = PAD_R3;

WEAK PadButton BINDING_PAUSE = PAD_SELECT;
